import type { Metadata } from "next";
import { Box, Grommet, grommet as grommetTheme } from 'grommet';
import Sidebar from "./Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ height: '100%', margin: '0', padding: '0', boxSizing: 'border-box' }}>
        <Grommet theme={grommetTheme}>
          <Box align="start" justify="start" direction="row" margin={'0'} pad={'0'} height={'100%'} gap={'1.5rem'}>
            <Sidebar />
            <Box margin={{ top: '1.5rem' }}>
              {children}
            </Box>
          </Box>
        </Grommet>
      </body>
    </html>
  );
}
